export enum Routes {
  ROOT = '/',
  OUR_STORY = '/our-story',
  CONTACT_US = '/contact-us',
  NEWS = '/news',
  SIGN_IN = '/sign-in',
  SIGN_UP = '/sign-up',
  RESET_PASSWORD = '/reset-password',
  PRIVACY_POLICY = '/privacy-policy',
  TERMS_CONDITIONS = '/terms-conditions',
  READING_LIST = '/reading-list',
  SETTINGS = '/settings',
  TOPICS = '/topics',
  TOPIC = '/topic',
  STUDIO = '/studio',
}
