export enum Routes {
  ROOT = "/",
  OUR_STORY = "/our-story",
  CONTACT_US = "/contact-us",
  NEWS = "/news",
  SIGN_IN = "/sign-in",
  SIGN_UP = "/sign-up",
  VERIFY = "/verify",
  ACTIVATE = "/activate",
  RESET_PASSWORD = "/reset-password",
  PRIVACY_POLICY = "/privacy-policy",
  TERMS_CONDITIONS = "/terms-conditions",
  READING_LIST = "/reading-list",
  SETTINGS = "/settings",
  TOPIC = "/topic",
  TOPICS = "/topics",
  POST = "/post",
  STUDIO = "/studio",
}
